certificate/urls.py
from django.urls import path
from . import views


app_name = 'certificate'


urlpatterns = [
    path ('',views.all_certificate,name="all_certificate")
]

resume/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from project import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('project/<int:project_id>', views.detail, name='detail'),
    path('certificate/', include('certificate.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

certificate/models.py
from django.db import models

# Create your models here.

class Certificate(models.Model):
    title=models.CharField(max_length=50)
    image=models.ImageField(upload_to= 'resume/images/')
    url=models.URLField(blank=True)
    
    def __str__(self):    
        return self.title
    

project/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Project(models.Model):
    title=models.CharField(max_length=50)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to= 'resume/images/')
    url=models.URLField(blank=True)
    
    
    def __str__(self):    
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={
            'project_id': self.id
            })
    
    

certificate/views.py
from django.shortcuts import render
from .models import Certificate


# Create your views here.

def all_certificate(request):
    certificates = Certificate.objects.all()
    context={
        'certificates':certificates
    }
    
    return render(request,'certificate/certificate.html', context)

project/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project

# Create your views here.

def index(request):
    projects=Project.objects.all()
    context={
        'projects':projects
    }
    return render (request,'project/index.html',context)

def detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    context = {
        'project':project
    }
    return render(request, 'project/detail.html' ,context)

certificate/templates/certificate/certificate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Resume</title>
        <!--Bootstrap-->
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        <link rel="icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <line href="{% static 'vendor/fontawesome.fees/css/all.main.css' %}" rel ="stylesheet"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">Siddharth Gautam</span>
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/img/SIDD.png' %}" alt="" /></span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="../#about">About</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="../#experience">Experience</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="../#education">Education</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="../#skills">Skills</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="../#interests">Interests</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="../#Projects">Projects</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#">CERTIFICATES AND WORKSHOP</a></li>

                </ul>
            </div>
        </nav>

             <!-- CERTIFICATES-->
            <section class="resume-section" id="Projects">
                <div class="resume-section-content">
                    <h2 class="mb-5">CERTIFICATES</h2>
                    <div class="row">
        {% for item in certificates %}
                <div class="card ml-5 mb-5" style="width: 22rem;">
                <img class="card-img-top"style="width: 22rem; height:18rem " src="{{ item.image.url }}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ item.title }}</h5>
                    <p class="card-text mb-2">{{ item.description|truncatechars:50}}</p>
                    {% if item.url %}
                    <a href="{{ item.url }}" class="btn btn-primary">Check website</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        </div>
           

         </div>
            </section>

           
        <!-- Bootstrap core JS-->
        <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js' %}"></script>
        <script src="{% static 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Third party plugin JS-->
        <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

project/templates/project/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Resume</title>
        <!--Bootstrap-->
        <line href="{% static 'vendor/bootstrap/css/bootstrap.main.css' %}" rel ="stylesheet"/>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <link rel="icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <line href="{% static 'vendor/fontawesome.fees/css/all.main.css' %}" rel ="stylesheet"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">Siddharth Gau</span>
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/img/SIDD.png' %}" alt="" /></span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#experience">Experience</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#education">Education</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#skills">Skills</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#interests">Interests</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#Projects">Projects</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'certificate:all_certificate'%}">CERTIFICATES AND WORKSHOP</a></li>
                </ul>
            </div>
        </nav>
            <!-- Projects-->
            <section class="resume-section" id="Projects">
                <div class="resume-section-content">
                    <h2 class="mb-5 ml-5">Project</h2>
                    <div class="row">
                <div class="card ml-5"">
                <center><img class="card-img-top"style="width: 18rem; height:18rem " src="{{ project.image.url }}" alt="Card image cap"></center>
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text mb-2">{{ project.description}}</p>
                    {% if project.url %}
                    <a href="{{ project.url }}" class="btn btn-primary">Check website</a>
                    {% endif %}
                </div>
            </div>
        </div>
            <!-- CERTIFICATES-->

         </div>
            </section>

           
        <!-- Bootstrap core JS-->
        <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js' %}"></script>
        <script src="{% static 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Third party plugin JS-->
        <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>